@getCEOName
Feature:
THIS FEATURE IS TO GET THE CEO NAME OF THE ORANGEHRM APP

Scenario Outline:
THIS TEST IS USED TO VERIFY THE CEO NAME

Given THE USER IS LOGGED IN SUCCESSFULLY AND IS ON THE HOMEPAGE
When THE USER CLICKS ON THE DIRECTORY OPTIONS ON THE MENU BAR
And THE USER SELECT THE JOB TITLE AS "CEO" FROM THE DROPDOWN
And CLICKS THE SEARCH BUTTON
Then THE USER SHOULD SEE THE CEO NAME AS <"CEO_NAME">

Examples:
|CEO_NAME|
|JOHN SMITH|